### ISSUE TITLE
Sending high priority message via GCM

### ISSUE THREAD

**Issue by jd-alexander** [Azure/azure-notificationhubs-samples#19]
I'm using Notification Hub to send noifications to my Android aplication. My question is by default what priority does the SDK use to send notifications and can this be configured. Based on what I  have seen on Google's website https://developers.google.com/cloud-messaging/concept-options?hl=en I can simply add the priority as part of the payload. However I am not sure how the underlying SDK handles this and if it adds a priority by default. This is what I did.  The notification is being sent with the code below but I'm wondering if the priority value has any effect.

 var payload = new
                    {
                        priority="high",
                        data = new
                        {
                            message = new
                            {
                                model.Title,
                                model.Time,
                                model.Message,
                                model.NotificationId,
                                model.NotificationType,
                                model.SenderFacebookId,
                                model.TargetId,
                                model.TargetUserFacebookId
                            }
                        }
                     };

                    var json = JsonConvert.SerializeObject(payload);
                    await hub.SendGcmNativeNotificationAsync(json, Tag.UserDevice.GetStringValue() + deviceId);

**Comment by wesmc7777** [comment]
This should work as expected with Azure notification hubs being basically pass-through. The priority would be handled by GCM.
