### ISSUE TITLE
The Token obtained from the Token Provider is wrong

### ISSUE THREAD

**Issue by satishgunjal** [Azure/azure-notificationhubs-samples#26]
Hi,

I am able to send toast notification to my Android app from Azure portal(using Debug) but getting below error when i tried sending toast notification using python script mentioned in this post.

C:\Users\satish.gunjal\Google Drive\My Projects\Home Automation\Source Code\Python-RaspberryPi>py NotificationHub.py

--- REQUEST ---

URI: https://cavenotificationhub-ns.servicebus.windows.net/cavenotificationhub/messages?api-version=2013-10&test

Headers: {

"Authorization": "SharedAccessSignature sig=7Xtx/WAhd4QsnYBS9Ttmimb6znTLucMhBcyWCeqAO7k%3D&se=1451236361&skn=DefaultFullSharedAccessSignature&sr=https%3a%2f%2fcavenotificationhub-ns.servicebus.windows.net%2fcavenotificationhub"

"Content-type": "application/json"

"ServiceBusNotification-Format": "gcm"

}

--- END REQUEST ---

send: b'POST https://cavenotificationhub-ns.servicebus.windows.net/cavenotificationhub/messages?api-version=2013-10&test HTTP/1.1\r\nHost: cavenotificationhub-ns.servicebus.windows.net\r\nAccept-Encoding: identity\r\nContent-Length: 27\r\nAuthorization: SharedAccessSignature sig=7Xtx/WAhd4QsnYBS9Ttmimb6znTLucMhBcyWCeqAO7k%3D&se=1451236361&skn=DefaultFullSharedAccessSignature&sr=https%3a%2f%2fcavenotificationhub-ns.servicebus.windows.net%2fcavenotificationhub\r\nServiceBusNotification-Format: gcm\r\nContent-type: application/json\r\n\r\n{"data": {"msg": "Hello!"}}'

reply: 'HTTP/1.1 201 Created\r\n'

header: Transfer-Encoding header: Content-Type header: Server header: Date

--- RESPONSE ---

201 Created

Transfer-Encoding: chunked

Content-Type: application/xml; charset=utf-8

Server: Microsoft-HTTPAPI/2.0

Date: Sun, 27 Dec 2015 17:07:45 GMT

b'<NotificationOutcome xmlns="http://schemas.microsoft.com/netservices/2010/10/servicebus/connect" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Success>3</Success><Failure>2</Failure><Results><RegistrationResult><ApplicationPlatform>gcm</ApplicationPlatform><PnsHandle>APA91bFJeOUUJnrxRNn9XqLu3pAz4nAMc-XeDSv08WRhilWz9MLaEgMZd1rdM0OBcrEoDdbtBANhW9HdTt4kCL18RHwrzYzu7zuYsq1xX5D75C1B1I7KEg-f5FGqkRtUR4j662J3gpfJMRppYgD0mu8eWMUHI_OcwA</PnsHandle><RegistrationId>2336285013042121653-349777072634954856-8</RegistrationId><Outcome>The Notification was successfully sent to the Push Notification System</Outcome></RegistrationResult><RegistrationResult><ApplicationPlatform>gcm</ApplicationPlatform><PnsHandle>APA91bFYbphBeym6XQnqzZIdbkxHCzJsiFoDaNWZG2E5tuiUMwgcFOA_5lzE3m2YIciFBwxbFaZ_HizKgknZQzHVo1bhKbOrCuZ_Ins9P4XQM945lDXyajtpisYwapMzhv3vx6HrlWNCNQ-gCJOBqhm2UCmR_x1hHg</PnsHandle><RegistrationId>4897321139793257950-7056394320734961166-8</RegistrationId><Outcome>The Notification was successfully sent to the Push Notification System</Outcome></RegistrationResult><RegistrationResult><ApplicationPlatform>gcm</ApplicationPlatform><PnsHandle>APA91bHBCBMOfJBNxQJfuHJIoma3p1ce_QynFVtKjDqHNxnLu5123SX-Xrv89ZZqC8JfK_aR1_3_Lc1zOWfrCN1xjDQIigkbcRz2JnW7G5nKg58sEVmCt9MmyehUcKnagJv3cQOVwsgr1Cu19vY9lri-AzAGn8zyvw</PnsHandle><RegistrationId>5663979817954802028-4194468470604299517-8</RegistrationId><Outcome>The Notification was successfully sent to the Push Notification System</Outcome></RegistrationResult><RegistrationResult><ApplicationPlatform>gcm</ApplicationPlatform><PnsHandle>APA91bHgn6cUOzl4Nkoo6C0OZedAXqY0sByqC2TuOhOmFPqFnZSvupWueKAJTUcruRgeK53YrsYMQun9Fk5E8Ud2zXiIX6DCv6uIBmLF2Se84zZ4Ed8UdiKxsW2fUUKm8bZSe2TCjR3a9oEzT34XtnGYJyfnL_aAVw</PnsHandle><RegistrationId>7848887551469475729-2479125434514584337-8</RegistrationId><Outcome>The Token obtained from the Token Provider is wrong</Outcome></RegistrationResult><RegistrationResult><ApplicationPlatform>gcm</ApplicationPlatform><PnsHandle>APA91bEIcQGufx0pXiEr2SUx-e4UI9mlF9v6OH4U_2eRU-suQXe1xCFJvdQYMvSy3JxctxxDX2M56pOKlIEBQEexSzQU8XM_dcXv0tOw87iOfFssX7irPn_ov8PP68LqBKFx6NfnXd-f</PnsHandle><RegistrationId>8090852208034026590-7000564859488873545-8</RegistrationId><Outcome>The Token obtained from the Token Provider is wrong</Outcome></RegistrationResult></Results></NotificationOutcome>'

--- END RESPONSE ---

**Comment by hirandesai** [comment]
I'm facing same issue but I'm not able to even send from azure portal
