### ISSUE TITLE
WP8.1 Silverlight Unauthorized

### ISSUE THREAD

**Issue by jieverson** [Azure/azure-notificationhubs-samples#37]
I'm getting Unauthorized when trying to use the PushToSLPhoneApp example. I've put my Identity tag at Package.appxmanifest:
`<Identity Name="...." Publisher="...." Version="...." />`

And I've also set my notificationHubName and connectionString at MainPage.cs/RegisterToReceiveNotifications.

At Azure Portal, I've set my Package SID and Security Key at WNS Settings.

**Comment by jwargo** [comment]
@jieverson I'm sorry, but since this is so old, I'm assuming you've figured it out or moved on.
