### ISSUE TITLE
Push Sharp on actual iOS device

### ISSUE THREAD

**Issue by marcbraun** [Azure/azure-notificationhubs-samples#38]
Works fine on iOS simulator.

**Throws the following message when building for device:**
Error MT2002: Failed to resolve "System.Reflection.Emit.ILGenerator" reference from "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" (MT2002)

Is it a problem with dynamic code generation which is forbidden by Apple?

**Comment by dpypin** [comment]
Could provide more details about this issue? It is hard to figure out what you are trying to do with PushSharp, NotificationHubs, iOS, .NET (Xamarin?).

**Comment by marcbraun** [comment]
Hi Dmitry

I want to send push notifications (via Azure) from one iOS device to other iOS devices.

I can the run the small testing app in the simulator but cannot build it for a device.
(you need to update the references to your libraries)

regards

[PushSharpTester.zip](https://github.com/Azure/azure-notificationhubs-samples/files/329324/PushSharpTester.zip)

**Comment by dpypin** [comment]
According to attached zip file you are trying to use PushSharp library, so I'd suggest you ask questions on it's official GitHub page (https://github.com/Redth/PushSharp). This repository contains samples for Azure Notification Hubs which you are not using in your source code.
