### ISSUE TITLE
Python SDK doesn't support iOS silent or scheduled pushes

### ISSUE THREAD

**Issue by mattdkerr** [Azure/azure-notificationhubs-samples#41]
I'm interested in making a pull request to add support - what guidelines should I be following, and are there any considerations that should be taken into account? I am implementing this primarily for Python 2.7, so I have also updated the sample to work within that context.

**Comment by mattdkerr** [comment]
Also adding support for direct push

**Comment by mattdkerr** [comment]
Ping

**Comment by jwargo** [comment]
@mattdkerr for these samples?  Just submit it and we'll make it work.
