### ISSUE TITLE
What is the right way to unregister azure notifications

### ISSUE THREAD

**Issue by eriknyk** [Azure/azure-notificationhubs-samples#50]
Hi when the user logged out from the app, I won't to receive more notifications,
however actually it is still receiving notification even when user is logged out,
on logout routine I'm calling to:

```
NotificationsManager.stopHandlingNotifications(contextProvider.get());
```

however I'm still getting notification, I would appreciate any help.

Best Regards.

**Comment by d1mnewz** [comment]
I think, the right way is to use DeleteRegistrationAsync method on the hub client itself. 
However, there are some people with the same [problem](https://github.com/Azure/azure-notificationhubs/issues/31)
