### ISSUE TITLE
Not receiving rich notifications

### ISSUE THREAD

**Issue by technificentConsulting** [Azure/azure-notificationhubs-samples#52]
NotificationExtensionService is installed, Provisioning is correct, Permissions set, Certs exported/imported and associated properly I get the notifications but no buttons, no images.

Visual Studio 2017 
Xamarin ios 11.4.1 on phone and ipad

I've tried swiping down, 3d touch, swipe left on notification center notification and choose View.  Nothing displays.  I can't figure out how to debug the notification service but my breakpoints are never hit.

I'm using this payload to test to successfully send
{
    "aps" : {
        "alert" : {
            "title" : "Game Request",
            "body" : "Bob wants to play poker",
            "action-loc-key" : "calendar"
            },
        "badge" : 1,
        "sound" : "default",
        "mutable-content" : 1
    },
    "data" :{        
        "attachment-url": "https://m.popkey.co/987552/NGLb3.gif"
    },
}

**Comment by jwargo** [comment]
I'm sorry you didn't get a response to this, have you made any progress?  Which sample app are you using?

**Comment by jwargo** [comment]
@technificentConsulting it's been more than a month with no response, so I'm going to close this. Please let us know if you still need help.
