### ISSUE TITLE
Registration issue with oreo

### ISSUE THREAD

**Issue by wasimshigri** [Azure/azure-notificationhubs-samples#55]
I am using Azure Could Messaging with andorid. It is working fine on device with android 6. When i run it on android 8, it ie giving error on following line.

NotificationHub hub = new NotificationHub(getNotificationHubName(),
getNotificationHubConnectionString(), this);
hub.register(FCM_token, tags).getRegistrationId();

it is giving following error on the code "hub.register(FCM_token, tags)":

"javax.net.ssl.SSLHandshakeException: Chain validation failed."

I iterated the code in deep to azure library. And i found that it is giving the error on exactly the following line

AndroidHttpClient.newInstance(getUserAgent()).execute(request);

**Comment by jwargo** [comment]
@wasimshigri were you able to resolve your issue?  I'm sorry this sat so long, I recently took over as PM and I'm cleaning up old issues.

**Comment by jwargo** [comment]
No response, so closing issue.
