### ISSUE TITLE
Use WindowsAzureMessaging in a Swift framework project on iOS

### ISSUE THREAD

**Issue by johnqh** [Azure/azure-notificationhubs-samples#59]
I couldn't get it to work. How do I make the project import the headers?

**Comment by jwargo** [comment]
Are you using one of the samples? Which one?

**Comment by shaqian** [comment]
I have a gist on using Azure Notification Hubs in Swift. Refer to Step 4 to import the headers.
https://gist.github.com/shaqian/79f31ecf5cd4825d279d49ffb3c701ae

**Comment by mpodwysocki** [comment]
@johnqh we now have a sample of using Swift with WindowsAzureMessaging https://github.com/Azure/azure-notificationhubs-ios/tree/master/Samples/Swift
