### ISSUE TITLE
Test Messages From Azure Not Showing Up on Device If App Not Running

### ISSUE THREAD

**Issue by JeffHoffelner** [Azure/azure-notificationhubs-samples#69]
When I send a test message from Azure to a Android Xamarin Forms application the message does not show up unless the application is running and in the foreground.

**Comment by jwargo** [comment]
@JeffHoffelner The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
