### ISSUE TITLE
FCM not working

### ISSUE THREAD

**Issue by Tjalle** [Azure/azure-notificationhubs-samples#72]
Hello,

This sample still uses gcm, which will stop working the 29th of may.
I'm trying to upgrade this to fcm, but it does not work.
Too bad the sample code has not been updated to use fcm as well, otherwise that might help.

Can you update this example?

Thank you,

Tjalle

**Comment by jwargo** [comment]
@Tjalle We're updating the docs and the samples. As I understand from Google's documentation this won't stop working. We've already done the work in the SDK to accommodate Google's change.

**Comment by Tjalle** [comment]
Thanks for your reply, 
It does seem they will continue to support this for external services, but I would like to upgrade asap. Because it will affect android Q users and it limits features because it's a legacy system.
( quote :
Note that client SDKs and GCM tokens will continue to work indefinitely. However, you won't be able to target the latest version of Google Play Services in your Android app unless you migrate to FCM.

https://developers.google.com/cloud-messaging/faq?utm_source=gcm-deprecation-last-round-msa
)

I'm looking forward to the update of the documentation so I can implement the update and use the latest version from my php server.

Thank you in advance.

**Comment by jwargo** [comment]
@Tjalle we apparently have an issue we're fixing (the fix is in, we're waiting to deploy) that fixes some FCM issues.
