### ISSUE TITLE
Error using the Cordova Sample

### ISSUE THREAD

**Issue by folego** [Azure/azure-notificationhubs-samples#74]
I am getting an error during the build of the app using the sample for Apache Cordova. 
I solved upgrading the cordova version, removing the android platform and adding again. I think will be better to updathe the solution here to avoid future issues with new users.

Do you have any plans to have a sample for Ionic 4?

Sample error:
`Plugin doesn't support this project's cordova-android version. cordova-android: 6.2.3, failed version requirement: >=7.1.0
Skipping 'cordova-azure-notification-hubs' for android`

Commands used:
`npm install -g cordova` --> upgrade Cordova
`cordova platform remove android` --> Remove current Android platform
`cordova platform add android` --> Install Android platform again witht the plugins

**Comment by jwargo** [comment]
@folego yeah, that's just the nature of Cordova projects. I'll take a look at refreshing it. 
To your other question, take a look at #56 .

**Comment by folego** [comment]
Dear @jwargo,

I was able to create an Ionic 4 application with the Cordova plugin using the same approach of the Ionic v3 sample. I believe it's not the most elegant way to call the plugin directly as a global variable, but works. It's my first Ionic project, and I believe there is a way to create a wrapper for the plugin (help will be very appreciated). What do you think? I will try to if I will have time to do that in the next days. Let you know if you are interested, maybe could be our sample for Ionic 4?

I am glad to help.

**Comment by jwargo** [comment]
@folego What I encountered with the Ionic 4 version was an incompatibility on the Capacitor side and I was just going to ask them to help me fix it. If you have something that works, send it over and I'll take a look.
