### ISSUE TITLE
Failed to install 'cordova-azure-notification-hubs': CordovaError: Version of installed plugin: "cordova-support-google-services@1.3.1" does not satisfy dependency plugin requirement "cordova-support-google-services@~1.2.0". Try --force to use installed plugin as dependency.     at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:544:43     at process._tickCallback (internal/process/next_tick.js:68:7)

### ISSUE THREAD

**Issue by benskarunya** [Azure/azure-notificationhubs-samples#79]
Hi, i am getting this error ionic 3 android

**Comment by jwargo** [comment]
@benskarunya the error message provides you with instructions for how to resolve it. Have you followed those instructions?

We provided the sample application as an example for how to use Azure Notification Hubs in an Ionic application. We do not provide support for third-party plugins or frameworks. The error you're receiving is a plugin dependency issue and you must follow standard Ionic/Cordova troubleshooting processes to resolve the issue.
