### ISSUE TITLE
Node.js sample

### ISSUE THREAD

**Issue by ankitwww** [Azure/azure-notificationhubs-samples#80]
Recently I added notification hub into my Node.js application. While the tutorial was great, I thought to check whether you guys are planning to add a Node.js sample. 

Why I am asking - I would like to add it and send a PR :)

**Comment by jwargo** [comment]
@ankitwww that's the beauty of open source projects, the ability to submit a PR with fixes or new stuff. Submit away and we'll consider it.  We have style and supportability to consider, plus how samples 'fit' with others, but we're happy to have community help here.
