### ISSUE TITLE
ERROR: No matching client found for package name 'com.xxx.xxx'

### ISSUE THREAD

**Issue by sas1981ec** [Azure/azure-notificationhubs-samples#82]
I followed all the steps but when executing ionic run android I get that error

**Comment by sas1981ec** [comment]
_ resolved_

**Comment by kkamperschroer** [comment]
Hey! I see you figured it out, but is there something that you found to be misleading or incorrect in the ionic steps? Thanks!

**Comment by jwargo** [comment]
@sas1981ec the Ionic sample is provided as-is, we publish it only to show you an example of how to use Ionic with Azure Notification Hubs. We do not provide support for Ionic or getting the application running on your system.
