### ISSUE TITLE
IONIC 4 Not receiving push notification when app in background

### ISSUE THREAD

**Issue by argonaut1** [Azure/azure-notificationhubs-samples#87]
Getting push notifications inside the app ( through alert box)  but when the app is in background there is no notification in status bar. When I open the app, again, the new message is shown in alert box.

**Comment by jwargo** [comment]
Please refer to [Using Azure Notification Hubs in Apache Cordova and Ionic Apps](https://techcommunity.microsoft.com/t5/azure-developer-community-blog/using-azure-notification-hubs-in-apache-cordova-and-ionic-apps/ba-p/1056685). 

It explains that on Ionic 4, Ionic Capacitor's Push plugin processes the notification when it arrives on the device.  You'll have to work with Ionic on that one, it's out of our hands
